common_config: &common_config
  durable: true
  type: direct
  arguments: {}

exchanges:
  player:
    <<: *common_config
    contexts:
      subscription:
        exchange_name: player.subscription
        queues:
          broadcast_notification:
            queue_name: broadcast_notification
            routing_key: player.subscription.broadcast_notification
            durable: true
          create_notification:
            queue_name: create_notification
            routing_key: player.subscription.create_notification
            durable: true
  delayed_messages:
    <<: *common_config
    type: x-delayed-message
    arguments: { "x-delayed-type": "direct" }
    contexts:
      subscription:
        exchange_name: delayed_messages.subscription
        queues:
          delete_notification:
            queue_name: delete_notification
            routing_key: delayed_messages.subscription.delete_notification
            durable: true